-- Local development seed (DEVELOPMENT ONLY — never use in staging/production).
--
-- Development accounts (password for all): LunchTest123!
--   owner@lunch.test
--   hr@lunch.test
--   accounts@lunch.test
--   staff1@lunch.test
--   staff2@lunch.test
--
-- Load with: npx supabase db reset
-- See docs/development-seed.md

-- NOTE: Supabase CLI executes seed SQL without psql meta-commands.
-- Fixture body lives in supabase/seeds/development.sql and is included below
-- by keeping a single sql_paths entry in config.toml.
